### ISSUE TITLE
训练很久，区域边缘一直有一些小点消失不掉

### ISSUE THREAD

**Issue by lindadamama** [fudan-zvg/SeaFormer#12]
![config](https://user-images.githubusercontent.com/48863486/222690344-a53aca70-4ea2-4601-9965-59cc4435a65c.PNG)
![Figure_1](https://user-images.githubusercontent.com/48863486/222686004-d148279c-37d5-4445-8055-3f17c3f14af2.png)
![Figure_2](https://user-images.githubusercontent.com/48863486/222689605-c3ccc2ea-dc9f-47eb-8544-a4be1832e4df.png)

**Comment by wwqq** [comment]
@lindadamama 你好，我随机测试了2000张图像，没有出现这样的情况，可视化结果已上传至网盘https://pan.baidu.com/s/1UU5O_VsKStQm0_DdOkWzhA (seaf)。另外根据你提供的图像文件名没有找到这张图像，pascal context数据集上训练的模型在自定义数据上有什么表现尚不清楚。

**Comment by lindadamama** [comment]
问题已经解决了，谢谢
