### ISSUE TITLE
关于代码的两个疑问

### ISSUE THREAD

**Issue by Ifjmww** [fudan-zvg/SeaFormer#13]
作者您好，您和您团队的工作非常出色，我对SeaFormer模型很感兴趣，在阅读完代码后有以下两个疑问：
1.https://github.com/fudan-zvg/SeaFormer/blob/cd1d0092503215349ae4670aa80b03dee4d9a385/seaformer-seg/mmseg/models/backbones/seaformer.py#L456-L463  
为什么是在i==1时才存入输出结果，按照论文图示，应该是i==0是存入输出结果。

2.https://github.com/fudan-zvg/SeaFormer/blob/cd1d0092503215349ae4670aa80b03dee4d9a385/seaformer-seg/mmseg/models/decode_heads/light_head.py#L81
最后使用的cls_seg函数并没有进行BN操作，这与论文图中所示不符。

![幻灯片1](https://user-images.githubusercontent.com/46148695/223382513-3d347916-83ac-4ab5-ace5-b37f15a59269.PNG)

以上两个问题您能否解答一下，不胜感激！

**Comment by wwqq** [comment]
@Ifjmww 您好
**1**.Shared STEM包含smb1和smb2，smb1四倍下采样，smb2二倍下采样。1/8下采样后的MV2↓2和MV2两个模块组成smb3。所以应该是i=1存入结果。
**2**.感谢纠正！这里只有conv。

**Comment by Ifjmww** [comment]
感谢您的回复！
