### ISSUE TITLE
关于LightHead的一些问题

### ISSUE THREAD

**Issue by 3DGGroup** [fudan-zvg/SeaFormer#14]
作者您好，我在LightHead中并没有找到上采样操作，Fusion_block中的上采样，也仅仅是将图片尺寸恢复至经Shared STEM处理后的八倍下采样大小，请问网络是在哪里将图片尺寸恢复到输入时的大小呢？

**Comment by Junye-Chen** [comment]
> 作者您好，我在LightHead中并没有找到上采样操作，Fusion_block中的上采样，也仅仅是将图片尺寸恢复至经Shared STEM处理后的八倍下采样大小，请问网络是在哪里将图片尺寸恢复到输入时的大小呢？

我也遇到了同样的问题，请问你们解决了吗？我看文章里面也没有对这个部分进行说明。

**Comment by wwqq** [comment]
上采样: 
Train: https://github.com/fudan-zvg/SeaFormer/blob/cd1d0092503215349ae4670aa80b03dee4d9a385/seaformer-seg/mmseg/models/decode_heads/decode_head.py#L235
Test: https://github.com/fudan-zvg/SeaFormer/blob/cd1d0092503215349ae4670aa80b03dee4d9a385/seaformer-seg/mmseg/models/segmentors/encoder_decoder.py#L75
