### ISSUE TITLE
How would we scale the output from 1/8 resolution to 1?

### ISSUE THREAD

**Issue by SXKJames** [fudan-zvg/SeaFormer#18]
The current output of the segmentation head is 1/8 the resolution of the original input. Is there a recommended segmentation head to use that would scale the 1/8 output from the backbone to the original input size?

Thanks,
James

**Comment by 9527950** [comment]
I need to design a decoder composed of transposed convolutions to transform the downsampled 1/8 size back to the original input size. How should I proceed? Can you share some code for this part?

**Comment by wwqq** [comment]
Upsampling code: https://github.com/fudan-zvg/SeaFormer/blob/cd1d0092503215349ae4670aa80b03dee4d9a385/seaformer-seg/mmseg/models/decode_heads/decode_head.py#L235

**Comment by SXKJames** [comment]
Ok, so the output is just bilinear upsampled to the original size. Thanks!
