### ISSUE TITLE
I can't find spatial branch in the code

### ISSUE THREAD

**Issue by vanyuming** [fudan-zvg/SeaFormer#4]
you have proposed spatial branch in your paper,but i can't  find it in your code.the code has a Fusion_Block class,but it never been referenced in th code.

**Comment by wwqq** [comment]
sptial branch and fusion block are here https://github.com/fudan-zvg/SeaFormer/blob/f64a6b5a5bfc72d91fbeae9ac4f54cccd72e5fe4/seaformer-seg/mmseg/models/decode_heads/light_head.py#L69

**Comment by vanyuming** [comment]
> 

thanks!
